let n = 10 
lol()
function lol (e){
try{
console.log(e,)
} catch (err){
console.log(err,)
}
}
